// micro-react-cra-app/src/views/home/index.js
import React, { useState, useEffect, useRef } from "react"
import { useImmer } from "use-immer";
import {Row, Col, Card, message} from 'antd'
import { RocketOutlined, GroupOutlined, GoldOutlined, TrademarkCircleOutlined, StarOutlined } from '@ant-design/icons'
import { $Api } from '@@api'
import { FetchVisitsRule, FetchCapacityRule } from '@@components/Charts/UseFetchsRule'
import DashTypeChart from '@@components/Charts/DashTypeChart'
import ComChart from '@@components/Charts/ComChart'
import WeatherList from '@@components/OlulLists/WeatherLi'
import TeamsMsgList from '@@components/OlulLists/TeamsMsgs'
import ActiveApps from '@@components/OlulLists/ActiveApps'
import { clearPending } from '@@api/pendings'

export default function Home(props) {
  const IconArr = [ 
  //  <GroupOutlined /> , 
    <RocketOutlined />,
    <GoldOutlined /> , 
    <TrademarkCircleOutlined /> , 
    <StarOutlined />
  ]
  const corArrs = [
    ['bg-blue-light', 'bg-blue-dark'],
    ['bg-purple-light', 'bg-purple-dark'],
    ['bg-cyan-light', 'bg-cyan-dark'],
    ['bg-white', 'bg-green-dark']
  ]

  const VisitorsOptions = {
    title: "访问量统计",
    field: "visitors",
    defaultPeriod: 1*24*60*60
  }

  const CapacityOptions = {
    title: "源码容量占比",
    field: "capacity"
  }

  const { visitsData } = FetchVisitsRule(VisitorsOptions)
  const { capacityData } = FetchCapacityRule(CapacityOptions)

 const exOptsLine = {
   type: 'line',
  // periodOpts: [{name:"1天", value:1*24*60*60}, {name:"7天", value:7*24*60*60}, {name:"30天", value:30*24*60*60}],
  //  dateFormatter: function (value) {
  //    return $Moment(value).format('YYYY/MM/DD')
  //  },
  otherChartOpts: {
    isUpdate: true,
    isMerge: false,
    legendEvent: false
  }
 }

 const exOptsRing = {
   type: 'semiring',
  //  periodOpts: [{
  //    name: "1天",
  //    value: 1 * 24 * 60 * 60
  //  }, {
  //    name: "7天",
  //    value: 7 * 24 * 60 * 60
  //  }, {
  //    name: "30天",
  //    value: 30 * 24 * 60 * 60
  //  }],
   otherChartOpts: {
     isUpdate: true,
     isMerge: false,
     legendEvent: false
   }
 }
 const [reqProps, setReqProps] = useState(null)
 
 useEffect(() => {
   loadDataFn()

   return () => {
    //  cleanup
    clearPending()
   }
 }, [])

 async function loadDataFn() {
  const globalRes= await $Api.getGlobals() 
  // const errorCode = globalRes.statusCode > 200 ? globalRes.statusCode : false
  const weatherRes = await $Api.getWeathers()
  const teamsRes = await $Api.getTeamsMsg()
  const activitiesRes = await $Api.getActivities()

  // console.log("stars:", globalRes)
  setReqProps({ 
    globalData: globalRes.data, 
    weatherData: weatherRes.data,
    teamsData: {
      title: "社区评论",
      ...teamsRes
    },
    activitiesData: {
      title: "活跃应用",
      ...activitiesRes
    }
  })

 }

 return (
    <>
      <Row gutter={16}>
        {reqProps? (reqProps.globalData.map((el, index) => <Col key={index} xs={24} sm={12} md={12} lg={6} xl={6}>
          <div className={`box-top ${corArrs[index][0]}`}>
            <figure className={corArrs[index][1]}>{IconArr[index]}</figure>
            <section>
              <h5>{el.value}{index===0?(<span>个</span>):null}</h5>
              <p>{el.cname}</p>
            </section>
          </div>
        </Col>)) : null}
        {/* {JSON.stringify(props)} */}
      </Row>
      
      <Row gutter={16}>
        <Col xs={24} sm={12} md={14} lg={16} xl={18}>
          <DashTypeChart render={chartOpt => (<ComChart propChartOpt={chartOpt} />)} propData={visitsData} exOption={exOptsLine}/>
        </Col>
        <Col xs={24} sm={12} md={10} lg={8} xl={6}>
          <DashTypeChart render={chartOpt => (<ComChart propChartOpt={chartOpt} />)} propData={capacityData} exOption={exOptsRing}/>
        </Col>
      </Row>

      {reqProps? (<Row gutter={16}>
        <Col xs={24} sm={12} md={14} lg={16} xl={18}>
          <WeatherList propWeather={reqProps.weatherData}/>
          <TeamsMsgList propTeams={reqProps.teamsData}/>
        </Col>
        <Col xs={24} sm={12} md={10} lg={8} xl={6}>
          <ActiveApps propActives={reqProps.activitiesData}/>
        </Col>
      </Row>): null }
    </>
  )
}

// micro-vuecli-app/src/views/Home.vue
<template>
  <div>
  <Row :gutter="16" v-if="!_.isEmpty(globalData)">
    <Col
      v-for="(el, index) in globalData"
      :key="index"
      :xs="24"
      :sm="12"
      :md="12"
      :lg="6"
      :xl="6"
      :xxl="6"
    >
      <div :class="corArrs[index][0]" class="box-top">
        <figure :class="corArrs[index][1]"><Icon :type="iconsType[index]" /></figure>
        <section>
          <h5>{{ el.value }} <span v-if="index === 0">个</span></h5>
          <p>{{ el.cname }}</p>
        </section>
      </div>
    </Col>
  </Row>
  <Row :gutter="16">
    <Col v-if="!_.isEmpty(weatherData)" :xs="24" :sm="12" :md="14" :lg="16" :xl="18" :xxl="18">
      <WeatherList :propWeather="weatherData"/>
      <TeamsMsgList :propTeams="teamsData"/>
    </Col>
    <Col :xs="24" :sm="12" :md="10" :lg="8" :xl="6" :xxl="6">
      <ActiveApps :propActives="activitiesData"/>
    </Col>
  </Row>
  </div>
</template>
<script>
  // @ is an alias to /src
  import WeatherList from '@/components/OlulLists/WeatherLi.vue'
  import TeamsMsgList from '@/components/OlulLists/TeamsMsgs.vue'
  import ActiveApps from '@/components/OlulLists/ActiveApps.vue'

  export default {
    name: "Home",
    components: { WeatherList, TeamsMsgList, ActiveApps },
    data() {
      return {
        iconsType: ["md-jet", "ios-grid", "md-planet", "md-star-outline"],
        corArrs: [
          ["bg-blue-light", "bg-blue-dark"],
          ["bg-purple-light", "bg-purple-dark"],
          ["bg-cyan-light", "bg-cyan-dark"],
          ["bg-white", "bg-green-dark"]
        ],
        VisitorsOptions: {
          title: "访问量统计",
          field: "visitors",
          defaultPeriod: 1 * 24 * 60 * 60
        },
        CapacityOptions: {
          title: "源码容量占比",
          field: "capacity"
        },
        globalData: [],
        weatherData: [],
        teamsData: {
          title: "社区评论",
          data: []
        },
        activitiesData: {
          title: "活跃应用",
          data: []
        }
      }
    },
    created: function() {
      this.loadDataFn()
    },
    methods: {
      async loadDataFn() {
        const globalRes = await this.$Api.getGlobals()
        this.globalData = globalRes.data
        const weatherRes = await this.$Api.getWeathers()
        this.weatherData = weatherRes.data
        // const errorCode = globalRes.statusCode > 200 ? globalRes.statusCode : false
        // await this.$nextTick(function () {
        //   // DOM 现在更新了
        //   // `this` 绑定到当前实例
        // })
        const teamsRes = await this.$Api.getTeamsMsg()
        this.teamsData.data = teamsRes.data
        console.log("teams0:", this.teamsData.data)
        const activitiesRes = await this.$Api.getActivities()
        this.activitiesData.data = activitiesRes.data
      }
    }
  }
</script>
